branches:
    only:
    - master
language: node_js
node_js:
  - "12"
services:
  - docker

jobs:
  include:
    - stage: build
      before_script:
        - npm ci
      script:
        - docker build -t covidhelp/covidhelp-api:latest -t covidhelp/covidhelp-api:${TRAVIS_COMMIT::8} .
      after_success:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push covidhelp/covidhelp-api
    - stage: deploy
      before_script:
        - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out deploy_rsa -d
        - eval "$(ssh-agent -s)"
        - chmod 600 /tmp/deploy_rsa
        - ssh-add /tmp/deploy_rsa
        - ssh-keyscan ${APP_DOMAIN} >> ~/.ssh/known_hosts
      script:
        - ssh ${SSH_USER}@${APP_DOMAIN} "cd ~/${APP_FOLDER} && docker-compose pull && docker-compose up -d"