branches:
    only:
    - master
language: node_js
node_js:
  - "12"
services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - docker build -t covidhelp/covidhelp-api:latest -t covidhelp/covidhelp-api:${TRAVIS_COMMIT::8} .
      after_success:
        - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push covidhelp/covidhelp-api
    - stage: deploy
      before_script:
        - eval "$(ssh-agent -s)"
        - ssh-add <(echo "$SSH_DEPLOY_KEY" | base64 --decode) > /dev/null
        - ssh-keyscan ${APP_DOMAIN} >> ~/.ssh/known_hosts
      script:
        - ssh ${SSH_USER}@${APP_DOMAIN} "cd ~/${APP_FOLDER} && export APP_DOMAIN=${APP_DOMAIN} && export ACME_EMAIL=${ACME_EMAIL} && docker-compose pull && docker-compose up -d"