version: "3.7"
services:
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
      MONGO_INITDB_DATABASE: "community-helpdesk"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
